### ISSUE TITLE
Gsync Switch On/Off Label

### ISSUE THREAD

**Issue by TonyBirt** [kwizatz88/GsyncSwitch#2]
Hi, many thanks for the app, if you have a paypal I would like to donate.  Its not an issue as such but would it be an option to add a label if Gsync was currently in the On or Off state?  I use a LG CX and it uses the same response notification popup for Gsync being turned on or off.

**Comment by kwizatz88** [comment]
Hello, thanks for the donation suggestion, I added a link in the about section on the main page.
Actually the project consists of an exe that makes the Gsync switch called by a C# app, because I'm not so familiar with C++ integration in C# and Nvapi is only available in C++.

But I'm planning to convert it to C++ calls in my C# project, so I will be able to add the state of Gsync while switching.
I'm also planning to add more Nvidia drivers switches, like Video Super Resolution toggle and stuff like that.
So, just wait a bit, as soon as my C++ calls issue is fixed, your suggestion should come fast (for VSR toggle I'm waiting for Nvapi update, cause the current one doesn't integrate it)

**Comment by kwizatz88** [comment]
I made the changes with direct C++ calls and added the current Gsync state as asked, so I'm closing the issue

**Comment by kwizatz88** [comment]
Thanks a lot for the donation, I appreciate 👍👍👍
